import React from "react";

export const clothOptionsArray = [
  { id: 1, style: "casual", isChecked: false },
  { id: 2, style: "formal", isChecked: false },
  { id: 3, style: "work", isChecked: false },
  { id: 4, style: "sports", isChecked: false },
  { id: 5, style: "night-out", isChecked: false },
  { id: 6, style: "lounge-wear", isChecked: false },
  { id: 7, style: "rainy", isChecked: false },
  { id: 8, color: "white", hex: "#fff", isChecked: false },
  { id: 9, color: "gray", hex: "#7A8B8B", isChecked: false },
  { id: 10, color: "black", hex: "#000", isChecked: false },
  { id: 11, color: "blue", hex: "#1C86EE", isChecked: false },
  { id: 12, color: "red", hex: "#EE3B3B", isChecked: false },
  { id: 13, color: "pink", hex: "#FF82AB", isChecked: false },
  { id: 14, color: "beige", hex: "#E1C699", isChecked: false },
  { id: 15, color: "lightgreen", hex: "#C1FFC1", isChecked: false },
  { id: 16, color: "green", hex: "#2E8B57", isChecked: false },
  { id: 17, color: "gold", hex: "#FFB90F", isChecked: false },
  { id: 18, color: "brown", hex: "#8B4500", isChecked: false },
  { id: 19, color: "lightblue", hex: "#C4FFFD", isChecked: false },
  { id: 20, color: "purple", hex: "#7F09E3", isChecked: false },
  { id: 21, type: "top" },
  { id: 22, type: "bottom" },
  { id: 23, season: "summer" },
  { id: 24, season: "in-between" },
  { id: 25, season: "winter" },
];
